### ISSUE TITLE
GitHub Actions Deployment Setup

### ISSUE THREAD

**Issue by ShreySigh2912** [ShreySigh2912/react-kanban-todo#1]
Let's set up GitHub Actions for automatic deployment:

1. Create `.github/workflows/deploy.yml`:
```yaml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
```

This will automatically deploy our app when we push to main.
